### ISSUE TITLE
LuL

### ISSUE THREAD

**Issue by RivaTesu** [apr3ndi5/Minecraft-Auto-Clicker#2]
HardCoded xD

**Comment by apr3ndi5** [comment]
Sim, igual 90% dos seus repositórios que geralmente é algo que nunca irá ser usado (ao menos para você um ser humano inútil) ou é uma tentativa falha de dar fork que aparentemente não sabe a funcionalidade https://prnt.sc/103fvwt

**Comment by RivaTesu** [comment]
HeavyUser + de 1 ano para responder uma issue..

**Comment by apr3ndi5** [comment]
É que eu uso Internet Explorer
